apiVersion: v1
kind: PersistentVolume
metadata:
  name: facility-manager-service-pv
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: {{ .Values.facilitymanagerservice.storageCapacity }}
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.facilitymanagerservice.path }}