apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: facility-manager-service
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: quay.io/qiotmanufacturing/factory-facility-manager
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local