apiVersion: apps/v1
kind: Deployment
metadata:
  name: facility-manager-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: facility-manager-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/facility-manager-service/facility-manager-service-cm.yaml") . | sha256sum }}
      labels:
        app: facility-manager-service
        deploymentconfig: facility-manager-service
    spec:
      containers:
      - image: quay.io/qiotmanufacturing/factory-facility-manager
        imagePullPolicy: Always
        name: facility-manager-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: facility-manager-service
        - mountPath: /cert/
          name: facility-manager-service-1
          readOnly: true
        - mountPath: /certbootstrap/
          name: facility-manager-service-2
          readOnly: true
        - mountPath: /var/data/qiot/factory/data/
          name: streamservice
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: facility-manager
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: facility-manager-service
        name: facility-manager-service
      - name: facility-manager-service-1
        secret:
          defaultMode: 420
          secretName: facility-manager-service-secret
      - name: facility-manager-service-2
        secret:
          defaultMode: 420
          secretName: bootstrap-certificate-client
      - name: streamservice
        secret:
          defaultMode: 420
          secretName: stream-service-truststore
