apiVersion: v1
kind: Service
metadata:
  name: product-line-service
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product-line-service
    deploymentconfig: product-line-service
  sessionAffinity: None
  type: ClusterIP