apiVersion: v1
data:
  application.properties: |-
    quarkus.log.level=INFO
    quarkus.log.category."io.qiot.manufacturing".level=DEBUG
    quarkus.ssl.native=false
    quarkus.native.enable-all-security-services=false
    factoryproductline-api/mp-rest/url=http://product-line-service:8080
    facility-manager-api/mp-rest/url=http://facility-manager-service:8080
    quarkus.artemis.url=tcp://broker-service-hdls-svc:61616
    kafka.bootstrap.servers=stream-service-kafka-bootstrap-manufacturing-dev.apps.cluster-4ktth.4ktth.sandbox1357.opentlc.com:443
    kafka.ssl.truststore.location=/var/data/qiot/factory/data/streamservice.ts
    kafka.ssl.truststore.password=password
    kafka.security.protocol=SASL_SSL
    kafka.sasl.jaas.config={{ .Values.productionvalidatorservice.sasl }}
    kafka.sasl.mechanism=SCRAM-SHA-512
    mp.messaging.outgoing.telemetryproduction.connector=smallrye-kafka
    mp.messaging.outgoing.telemetryproduction.topic=telemetryproduction
    mp.messaging.outgoing.telemetryproduction.value.serializer=io.qiot.manufacturing.factory.productionvalidation.util.serializer.ProductionTelemetrySerializer
kind: ConfigMap
metadata:
  name: production-validator-service
