name: manufacturing-srv-factory-sno-install
facilitymanagerservice:
  path: "/var/hpvolumes/facility_manager_service"
  storageCapacity: 5Gi
  serial: "?"
  name: "?"
productionvalidatorservice:
  sasl: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="telemetry-producer" password="IXROfcbJbHbD";'
productlineservice:
  sasl: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="productline-consumer" password="UjlcgBjcs4fP";'