kind: Secret
apiVersion: v1
metadata:
  name: mongodb
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.MONGO_INITDB_ROOT_PASSWORD }}
  MONGODB_ADMIN_PASSWORD: {{ .Values.mongo.MONGODB_ADMIN_PASSWORD }}
  MONGODB_DATABASE: {{ .Values.mongo.MONGODB_DATABASE }}
  MONGODB_PASSWORD: {{ .Values.mongo.MONGODB_PASSWORD }}
  MONGODB_USER: {{ .Values.mongo.MONGODB_USER }}
type: Opaque