name: manufacturing-comp-factory-sno-install
amqbroker:
  size: 1
  brokerName: broker-service
  adminPassword: qiotmanufacturingpassword
  adminUser: qiotmanufacturing
  path: "/var/hpvolumes/amqbroker"
  storageCapacity: 5Gi
mongo:
  path: "/var/hpvolumes/mongodb"
  storageCapacity: 5Gi
  MONGO_INITDB_ROOT_USERNAME: qiotroot
  MONGO_INITDB_ROOT_PASSWORD: qiotrootpassword
  MONGODB_ADMIN_PASSWORD: qiotrootpassword
  MONGODB_DATABASE: qiot_manufacturing
  MONGODB_PASSWORD: qiotmanufacturingpassword
  MONGODB_USER: qiotmanufacturing
postgresql:
  path: "/var/hpvolumes/postgresql"
  storageCapacity: 5Gi
  POSTGRESQL_DATABASE: qiot_manufacturing
  POSTGRESQL_PASSWORD: qiotmanufacturingpassword
  POSTGRESQL_USER: qiotmanufacturing