apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: core-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/core-service/core-service-cm.yaml") . | sha256sum }}
      labels:
        app: core-service
        deploymentconfig: core-service
    spec:
      containers:
      - image: quay.io/qiotmanufacturing/factory-core
        imagePullPolicy: Always
        name: core-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: core-service
        - mountPath: /cert/
          name: core-service-2
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: core-service
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: core-service
        configMap:
          defaultMode: 420
          name: core-service
      - name: core-service-2
        secret:
          defaultMode: 420
          secretName: bootstrap-certificate-client
