apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.amqbroker.brokerName }}-{{ .Values.amqbroker.brokerName }}-ss-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.amqbroker.storageCapacity }}
  storageClassName: manual
  volumeName: amqbroker-pv