---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "amqbroker.fullname" . }}-secret
  labels:
    {{- include "amqbroker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "amqbroker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "amqbroker.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: secret
        image: "{{ .Values.oc.image.repository }}:{{ .Values.oc.image.tag }}"
        envFrom:
        - secretRef:
            name: keystore-endpoint-service-edge
        command:
        - /bin/bash
        - '-c'
        - |
            #!/bin/bash

            # Seems an issue with multiple cr instead of one....
            oc delete cr -lcert-manager.io/certificate-name=endpoint-service-edge
            sleep 80

            mkdir -p /tmp/edge
            oc extract secret/endpoint-service-edge /tmp/edge

            oc create secret generic endpoint-service-tls-secret \
            --from-file=broker.ks=keystore.p12 \
            --from-file=client.ts=truststore.p12 \
            --from-literal=keyStorePassword=$PASSWORD \
            --from-literal=trustStorePassword=$PASSWORD

            rm -fr /tmp/edge
