apiVersion: v1
kind: PersistentVolume
metadata:
  name: amqbroker-pv
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: {{ .Values.amqbroker.storageCapacity }}
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.amqbroker.path }}