---
apiVersion: v1
data:
  PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: keystore-endpoint-service-edge
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: endpoint-service-edge
  labels:
    cert-manager.io/certificate-name: endpoint-service-edge
spec:
  commonName: endpoint-service-edge-0-svc.{{ .Release.Namespace }}.svc
  dnsNames:
    - endpoint-service-edge-0-svc.{{ .Release.Namespace }}.svc
    - endpoint-service-edge-0-svc-rte.{{ .Release.Namespace }}.{{ .Values.amqbroker.certificate.baseDomain }}
    - endpoint-service-edge-0-svc-rte-{{ .Release.Namespace }}.{{ .Values.amqbroker.certificate.wildcardDomain }}
  issuerRef:
    name: factory
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: PASSWORD
        name: keystore-endpoint-service-edge
  secretName: endpoint-service-edge-secret
