apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: {{ .Values.amqbroker.brokerName }}
  application: {{ .Values.amqbroker.brokerName }}
spec:
  adminPassword: {{ .Values.amqbroker.adminPassword }}
  deploymentPlan:
    size: {{ .Values.amqbroker.size }}
    persistenceEnabled: false
    journalType: nio
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: aio
    jolokiaAgentEnabled: false
    image: placeholder
  adminUser: {{ .Values.amqbroker.adminUser }}
  console:
    expose: true
  acceptors:
    - name: edge
      port: 61617
      wantClientAuth: true
      expose: true
      needClientAuth: true
      sslEnabled: true
      protocols: core
      sslSecret: endpoint-service-tls-secret
      sslProvider: JDK
  upgrades:
      enabled: false
      minor: false
