---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "amqbroker.fullname" . }}-secret
  labels:
    {{- include "amqbroker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "amqbroker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "amqbroker.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: secret
        image: "{{ .Values.oc.image.repository }}:{{ .Values.oc.image.tag }}"
        envFrom:
        - secretRef:
            name: keystore-endpoint-service-edge
        command:
        - /bin/bash
        - '-c'
        - |
            #!/bin/bash

            # In case the certificate takes too long to get generated(Seems an issue with multiple cr instead of one...)
            # oc delete cr -lcert-manager.io/certificate-name=endpoint-service-edge -n factory
            sleep 10

            mkdir -p /tmp/edge
            oc extract secret/endpoint-service-edge-secret -n factory --to=/tmp/edge/

            oc create secret generic endpoint-service-tls-secret -n factory \
            --from-file=broker.ks=/tmp/edge/keystore.p12 \
            --from-file=client.ts=/tmp/edge/truststore.p12 \
            --from-literal=keyStorePassword=$PASSWORD \
            --from-literal=trustStorePassword=$PASSWORD

            rm -fr /tmp/edge
            
            # in an enterprise environment the "oc delete" MUST be replaced with LABEL SELECTOR
            oc delete pod broker-service-ss-0 -n factory
