apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: {{ .Values.amqbroker.brokerName }}
  application: {{ .Values.amqbroker.brokerName }}
spec:
  adminPassword: {{ .Values.amqbroker.adminPassword }}
  deploymentPlan:
    size: {{ .Values.amqbroker.size }}
    persistenceEnabled: false
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: aio
    jolokiaAgentEnabled: false
    image: placeholder
  adminUser: {{ .Values.amqbroker.adminUser }}
  console:
    expose: true
  acceptors:
    - name: edge
      port: 61617
      wantClientAuth: false
      expose: true
      needClientAuth: false
      sslEnabled: true
      protocols: core
      sslSecret: endpoint-service-tls-secret
      sslProvider: JDK
    - name: amqp
      protocols: amqp
      port: 5672
      needClientAuth: false
      wantClientAuth: false
  connectors:
    - name: connector0
      host: localhost
      port: 22222
      sslEnabled: false
      enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
  upgrades:
      enabled: false
      minor: false