kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registration-service-privileged
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: registration-service
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin