apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: registration-service
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: quay.io/qiotproject/all-registration
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local